### 서버 관리
server:
### 내장 WAS 관리
  port: 8080
  servlet:
    session:
      persistent: false

### 토큰 관리
jwt:
  ## 개인 키
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  ## 토큰 유효 시간
  access-token-valid-time: 300000 # (default: 5분)
  refresh-token-valid-time: 86400000 # (default: 24시간)

### Spring 관리
spring:
  datasource:
### h2 DB(default)
    driver-class-name: org.h2.Driver
###    다중 프로세스 접근 (File Mode)
    url: jdbc:h2:file:./db/h2/h2db;AUTO_SERVER=true
###    단일 프로세스 접근 (In-Memory Mode)
#    url: jdbc:h2:mem:testdb
### MariaDB
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3307/demo?rewriteBatchedStatements=true
    username: sa
    password:

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

### JPA 관리
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

### Security 관리
  security:
    ### OAuth2.0 사용여부 (default: false)
    oauth2-enabled: false
    oauth2:
      client:
        registration:
          google:
            client-id: demo
            client-secret: demo
            scope:
              - email
              - profile
          naver:
            client-id: demo
            client-secret: demo
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response