### 해당 프로젝트 경로 (default:~)
root-dir: C:\SecurityReference
#db-file-dir: ${root-dir}/db/h2/h2db

### 서버 관리
server:
  ### 내장 WAS 관리
#  port: 8080

### 토큰 관리
jwt:
#  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

### Spring 관리
spring:
  datasource:
### h2 DB(default)
#    driver-class-name: org.h2.Driver
###    다중 프로세스 접근 (File Mode)
#    url: jdbc:h2:file:${db-file-dir};AUTO_SERVER=true
###    단일 프로세스 접근 (In-Memory Mode)
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:

### JPA 관리
  jpa:
#    hibernate.ddl-auto: update
#    show-sql: true
